// ============================================================
// BASE DE DADOS LOCAL — SIMULANDO SUPABASE
//
// Analogia Python: é como ler um arquivo JSON ou um CSV com
// pd.read_csv('produtos.csv'). Este arquivo é o nosso "seed"
// inicial. Quando conectarmos o Supabase, esses dados serão
// migrados para lá e este arquivo deixará de ser necessário.
//
// Estrutura: lista de dicts → array de objetos TypeScript
// Em Python seria: produtos = [{"id": "abacate", ...}, ...]
// ============================================================

import type { Produto, ConfigCestaSemana } from "./types";

// Todos os produtos cadastrados, extraídos diretamente do PDF de requisitos.
// emEstoque: false por padrão — a Elizete ativa no painel admin.
// naCestaGrande / naCestaPequena: false por padrão — Elizete monta semanalmente.
export const PRODUTOS_INICIAIS: Produto[] = [
  // ─── CESTAS ───────────────────────────────────────────────
  // As cestas aparecem separadas na tela do cliente, mas também
  // podem ser adicionadas ao carrinho como item avulso
  {
    id: "cesta-grande",
    nome: "Cesta Grande",
    preco: 75.0,
    unidade: "cesta (~10-12 itens)",
    categoria: "Cestas",
    emEstoque: true,
    naCestaGrande: false,
    naCestaPequena: false,
    descricao: "Cesta semanal com 10 a 12 itens selecionados pela COMUNA.",
  },
  {
    id: "cesta-pequena",
    nome: "Cesta Pequena",
    preco: 55.0,
    unidade: "cesta (~9-10 itens)",
    categoria: "Cestas",
    emEstoque: true,
    naCestaGrande: false,
    naCestaPequena: false,
    descricao: "Cesta semanal com 9 a 10 itens selecionados pela COMUNA.",
  },

  // ─── FRUTAS ───────────────────────────────────────────────
  {
    id: "abacate",
    nome: "Abacate",
    preco: 8.0,
    unidade: "unidade",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
    descricao: "Abacate orgânico fresco.",
  },
  {
    id: "abacaxi-pequeno",
    nome: "Abacaxi Pequeno",
    preco: 15.0,
    unidade: "unidade",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "abacaxi-medio",
    nome: "Abacaxi Médio",
    preco: 15.0,
    unidade: "unidade",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "abio",
    nome: "Abio",
    preco: 10.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
    descricao: "Fruta tropical adocicada, rica em vitaminas.",
  },
  {
    id: "acerola",
    nome: "Acerola",
    preco: 5.0,
    unidade: "250g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
    descricao: "Rica em vitamina C. Ideal para sucos e vitaminas.",
  },
  {
    id: "ameixa-amarela",
    nome: "Ameixa Amarela",
    preco: 15.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "ameixa-vermelha",
    nome: "Ameixa Vermelha",
    preco: 15.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "amora",
    nome: "Amora",
    preco: 6.0,
    unidade: "250g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
    descricao: "Amora fresca orgânica.",
  },
  {
    id: "atemoia",
    nome: "Atemoia",
    preco: 10.0,
    unidade: "unidade",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
    descricao: "Fruta tropical com polpa cremosa e doce.",
  },
  {
    id: "bacupari",
    nome: "Bacupari",
    preco: 7.0,
    unidade: "250g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "banana-da-terra",
    nome: "Banana da Terra",
    preco: 18.0,
    unidade: "1kg",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "banana-de-fritar",
    nome: "Banana de Fritar",
    preco: 8.0,
    unidade: "1kg",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "banana-maca",
    nome: "Banana Maçã",
    preco: 10.0,
    unidade: "1kg",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "banana-nanica",
    nome: "Banana Nanica",
    preco: 12.0,
    unidade: "1kg",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "banana-ouro",
    nome: "Banana Ouro",
    preco: 12.0,
    unidade: "1kg",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "banana-prata",
    nome: "Banana Prata",
    preco: 9.0,
    unidade: "1kg",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "cabeludinha",
    nome: "Cabeludinha",
    preco: 6.0,
    unidade: "250g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
    descricao: "Fruta da Mata Atlântica, adocicada e aromática.",
  },
  {
    id: "cacau-fruta",
    nome: "Cacau Fruta",
    preco: 10.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
    descricao: "Cacau fresco in natura.",
  },
  {
    id: "caju",
    nome: "Caju",
    preco: 5.0,
    unidade: "100g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "caqui",
    nome: "Caqui",
    preco: 10.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "carambola",
    nome: "Carambola",
    preco: 10.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "coco-verde",
    nome: "Coco Verde",
    preco: 5.0,
    unidade: "unidade",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "figo",
    nome: "Figo",
    preco: 10.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "goiaba",
    nome: "Goiaba",
    preco: 9.0,
    unidade: "300g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "graviola",
    nome: "Graviola",
    preco: 7.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "inga",
    nome: "Ingá",
    preco: 5.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "jaboticaba",
    nome: "Jaboticaba",
    preco: 6.0,
    unidade: "250g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "jaca-no-pote",
    nome: "Jaca no Pote",
    preco: 10.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "jenipapo",
    nome: "Jenipapo",
    preco: 5.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "kiwi",
    nome: "Kiwi",
    preco: 20.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "laranja-bahia",
    nome: "Laranja Bahia",
    preco: 8.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "laranja-lima",
    nome: "Laranja Lima",
    preco: 6.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "laranja-pera",
    nome: "Laranja Pêra",
    preco: 7.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "lima",
    nome: "Lima",
    preco: 6.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "lima-da-persia",
    nome: "Lima da Pérsia",
    preco: 8.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "limao-cravo",
    nome: "Limão Cravo",
    preco: 4.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "limao-galego",
    nome: "Limão Galego",
    preco: 5.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "limao-siciliano",
    nome: "Limão Siciliano",
    preco: 7.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "limao-taiti",
    nome: "Limão Taiti",
    preco: 5.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "longan",
    nome: "Longan",
    preco: 10.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "maca-verde-importada",
    nome: "Maçã Verde Importada",
    preco: 15.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "maca-vermelha-importada",
    nome: "Maçã Vermelha Importada",
    preco: 15.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "maca-nacional",
    nome: "Maçã Nacional",
    preco: 15.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "mamao-caipira",
    nome: "Mamão Caipira",
    preco: 8.0,
    unidade: "800g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "mamao-formoso",
    nome: "Mamão Formoso",
    preco: 10.0,
    unidade: "800g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "mamao-havai",
    nome: "Mamão Havaí",
    preco: 10.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "mamao-papaya",
    nome: "Mamão Papaya",
    preco: 10.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "manga-bourbon",
    nome: "Manga Bourbon",
    preco: 10.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "manga-comum",
    nome: "Manga Comum ou Coquinho",
    preco: 5.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "manga-palmer",
    nome: "Manga Pálmer",
    preco: 8.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "manga-tommy",
    nome: "Manga Tommy",
    preco: 8.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "maracuja",
    nome: "Maracujá",
    preco: 10.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "melancia",
    nome: "Melancia",
    preco: 8.0,
    unidade: "1kg",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "melao",
    nome: "Melão",
    preco: 15.0,
    unidade: "1kg",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "mexerica-bergamota",
    nome: "Mexerica Bergamota",
    preco: 8.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "mexerica-murcote",
    nome: "Mexerica Murcote",
    preco: 8.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "morango",
    nome: "Morango",
    preco: 12.0,
    unidade: "250g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "nactarina",
    nome: "Nactarina",
    preco: 13.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "pera-nacional",
    nome: "Pera Nacional",
    preco: 10.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "pessego",
    nome: "Pêssego",
    preco: 15.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "pinha",
    nome: "Pinha",
    preco: 8.0,
    unidade: "400g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "pitaia",
    nome: "Pitaia",
    preco: 14.0,
    unidade: "400g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
    descricao: "Fruta exótica rica em antioxidantes.",
  },
  {
    id: "pitanga",
    nome: "Pitanga",
    preco: 8.0,
    unidade: "250g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "roma",
    nome: "Romã",
    preco: 10.0,
    unidade: "400g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "seriguela",
    nome: "Seriguela",
    preco: 5.0,
    unidade: "250g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "tamarindo",
    nome: "Tamarindo",
    preco: 10.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "tangerina",
    nome: "Tangerina",
    preco: 8.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "uva-isabel",
    nome: "Uva Isabel",
    preco: 20.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "uva-italia",
    nome: "Uva Itália",
    preco: 20.0,
    unidade: "500g",
    categoria: "Frutas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },

  // ─── VERDURAS E LEGUMES ───────────────────────────────────
  {
    id: "abobora-cabotia",
    nome: "Abóbora Cabotiá",
    preco: 8.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "abobora-moranga",
    nome: "Abóbora Moranga",
    preco: 4.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "abobora-seca",
    nome: "Abóbora Seca",
    preco: 4.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "abobora-seca-descascada",
    nome: "Abóbora Seca Descascada",
    preco: 5.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "abobora-italiana",
    nome: "Abóbora Italiana",
    preco: 8.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "abobora-menina",
    nome: "Abóbora Menina",
    preco: 8.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "acelga",
    nome: "Acelga",
    preco: 8.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "agriao",
    nome: "Agrião",
    preco: 6.0,
    unidade: "400g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "alface-americana",
    nome: "Alface Americana",
    preco: 8.0,
    unidade: "400g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "alface-crespa",
    nome: "Alface Crespa",
    preco: 7.0,
    unidade: "400g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "alface-lisa",
    nome: "Alface Lisa",
    preco: 8.0,
    unidade: "400g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "alface-roxa",
    nome: "Alface Roxa",
    preco: 8.0,
    unidade: "400g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "alho-branco",
    nome: "Alho Branco",
    preco: 8.0,
    unidade: "100g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "alho-japones",
    nome: "Alho Japonês",
    preco: 5.0,
    unidade: "200g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "alho-poro",
    nome: "Alho Poró",
    preco: 8.0,
    unidade: "200g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "almeirao-de-corte",
    nome: "Almeirão de Corte",
    preco: 6.0,
    unidade: "400g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "almeirao-catalunha",
    nome: "Almeirão Catalunha",
    preco: 5.0,
    unidade: "400g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "almeirao-pao-de-acucar",
    nome: "Almeirão Pão de Açúcar",
    preco: 6.0,
    unidade: "400g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "batata-inglesa",
    nome: "Batata Inglesa",
    preco: 8.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "batata-bolinha",
    nome: "Batata Bolinha",
    preco: 6.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "batata-doce",
    nome: "Batata Doce",
    preco: 7.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "batata-doce-laranja",
    nome: "Batata Doce Laranja",
    preco: 10.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "batata-doce-roxa",
    nome: "Batata Doce Roxa",
    preco: 10.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "batata-yacon",
    nome: "Batata Yacon",
    preco: 10.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "beldroega",
    nome: "Beldroega",
    preco: 5.0,
    unidade: "400g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "berinjela",
    nome: "Berinjela",
    preco: 6.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "bertalha",
    nome: "Bertalha",
    preco: 4.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "beterraba",
    nome: "Beterraba",
    preco: 8.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "brocolis",
    nome: "Brócolis",
    preco: 8.5,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "brocolis-ninja",
    nome: "Brócolis Ninja",
    preco: 10.0,
    unidade: "unidade",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "cambuquira",
    nome: "Cambuquira",
    preco: 5.0,
    unidade: "400g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "cana-descascada",
    nome: "Cana Descascada",
    preco: 8.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "cara",
    nome: "Cará",
    preco: 5.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "caruru",
    nome: "Carurú",
    preco: 4.0,
    unidade: "400g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "caxi",
    nome: "Caxí",
    preco: 7.0,
    unidade: "1kg",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "cebola",
    nome: "Cebola",
    preco: 10.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "cebola-roxa",
    nome: "Cebola Roxa",
    preco: 11.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "cebolete",
    nome: "Cebolete",
    preco: 5.0,
    unidade: "50g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "cebolinha",
    nome: "Cebolinha",
    preco: 4.0,
    unidade: "100g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "cenoura",
    nome: "Cenoura",
    preco: 9.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "chicoria",
    nome: "Chicória",
    preco: 5.0,
    unidade: "400g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "chuchu",
    nome: "Chuchu",
    preco: 7.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "couve",
    nome: "Couve",
    preco: 6.0,
    unidade: "400g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "couve-flor",
    nome: "Couve Flor",
    preco: 10.0,
    unidade: "400g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "couve-manteiga",
    nome: "Couve Manteiga",
    preco: 8.0,
    unidade: "400g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "ervilha",
    nome: "Ervilha",
    preco: 10.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "espinafre",
    nome: "Espinafre",
    preco: 7.0,
    unidade: "400g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "inhame",
    nome: "Inhame",
    preco: 6.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "jilo",
    nome: "Jiló",
    preco: 5.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "mandioca-com-casca",
    nome: "Mandioca com Casca",
    preco: 4.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "mandioca-descascada",
    nome: "Mandioca Descascada",
    preco: 6.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "mandioquinha-branca",
    nome: "Mandioquinha Branca",
    preco: 12.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "maxixe",
    nome: "Maxixe",
    preco: 8.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "milho-verde",
    nome: "Milho Verde",
    preco: 8.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "mostarda",
    nome: "Mostarda",
    preco: 5.0,
    unidade: "400g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "nabo",
    nome: "Nabo",
    preco: 8.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "pepininho",
    nome: "Pepininho",
    preco: 9.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "pepino-caipira",
    nome: "Pepino Caipira",
    preco: 6.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "pepino-comum",
    nome: "Pepino Comum",
    preco: 6.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "pepino-japones",
    nome: "Pepino Japonês",
    preco: 8.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "pimenta-biquinho",
    nome: "Pimenta Biquinho",
    preco: 8.0,
    unidade: "300g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "pimenta-cambuci",
    nome: "Pimenta Cambuci",
    preco: 7.0,
    unidade: "300g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "pimenta-dedo-de-moca",
    nome: "Pimenta Dedo de Moça",
    preco: 7.0,
    unidade: "200g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "pimenta-malagueta",
    nome: "Pimenta Malagueta",
    preco: 8.0,
    unidade: "300g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "pimentao-amarelo",
    nome: "Pimentão Amarelo",
    preco: 15.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "pimentao-verde",
    nome: "Pimentão Verde",
    preco: 10.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "pimentao-vermelho",
    nome: "Pimentão Vermelho",
    preco: 15.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "quiabo",
    nome: "Quiabo",
    preco: 8.5,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "rabanete",
    nome: "Rabanete",
    preco: 5.0,
    unidade: "300g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "repolho",
    nome: "Repolho",
    preco: 10.0,
    unidade: "800g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "rucula",
    nome: "Rúcula",
    preco: 6.0,
    unidade: "400g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "taioba",
    nome: "Taioba",
    preco: 5.0,
    unidade: "400g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "tomate-cereja",
    nome: "Tomate Cereja",
    preco: 12.0,
    unidade: "400g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "tomate-salada",
    nome: "Tomate Salada",
    preco: 9.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "vagem",
    nome: "Vagem",
    preco: 10.0,
    unidade: "500g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "vinagreira",
    nome: "Vinagreira",
    preco: 5.0,
    unidade: "400g",
    categoria: "Verduras e Legumes",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },

  // ─── ERVAS E TEMPEROS ─────────────────────────────────────
  {
    id: "alecrim",
    nome: "Alecrim",
    preco: 5.0,
    unidade: "100g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "alfavaca",
    nome: "Alfavaca",
    preco: 4.0,
    unidade: "100g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "arnica",
    nome: "Arnica",
    preco: 5.0,
    unidade: "100g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "babosa",
    nome: "Babosa",
    preco: 5.0,
    unidade: "100g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "capim-limao",
    nome: "Capim Limão",
    preco: 5.0,
    unidade: "100g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "capuchinho",
    nome: "Capuchinho",
    preco: 8.0,
    unidade: "100g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "carqueja",
    nome: "Carqueja",
    preco: 5.0,
    unidade: "100g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "cheiro-verde",
    nome: "Cheiro Verde",
    preco: 5.0,
    unidade: "200g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "coentro",
    nome: "Coentro",
    preco: 5.0,
    unidade: "200g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "colorau",
    nome: "Colorau",
    preco: 10.0,
    unidade: "100g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "curcuma-in-natura",
    nome: "Cúrcuma in Natura",
    preco: 5.0,
    unidade: "100g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
    descricao: "Raiz anti-inflamatória poderosa.",
  },
  {
    id: "erva-doce-organica",
    nome: "Erva Doce Orgânica",
    preco: 8.0,
    unidade: "100g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "estragon",
    nome: "Estragão",
    preco: 5.0,
    unidade: "100g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "gengibre",
    nome: "Gengibre",
    preco: 5.0,
    unidade: "100g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "guaco",
    nome: "Guaco",
    preco: 5.0,
    unidade: "200g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "hortela",
    nome: "Hortelã",
    preco: 5.0,
    unidade: "100g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "hortela-pimenta",
    nome: "Hortelã Pimenta",
    preco: 7.0,
    unidade: "100g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "manjericao",
    nome: "Manjericão",
    preco: 5.0,
    unidade: "100g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "melissa",
    nome: "Melissa",
    preco: 5.0,
    unidade: "100g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "menta",
    nome: "Menta",
    preco: 5.0,
    unidade: "100g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "oregano",
    nome: "Orégano",
    preco: 5.0,
    unidade: "100g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "oro-pro-nobis",
    nome: "Oro Pro Nobis",
    preco: 4.0,
    unidade: "100g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
    descricao: "Hortaliça nativa rica em proteínas.",
  },
  {
    id: "peixinho",
    nome: "Peixinho",
    preco: 5.0,
    unidade: "100g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "salsinha",
    nome: "Salsinha",
    preco: 4.0,
    unidade: "100g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "salvia",
    nome: "Sálvia",
    preco: 7.0,
    unidade: "100g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "tomilho",
    nome: "Tomilho",
    preco: 5.0,
    unidade: "100g",
    categoria: "Ervas e Temperos",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },

  // ─── PROTEÍNAS ────────────────────────────────────────────
  {
    id: "amendoim",
    nome: "Amendoim",
    preco: 20.0,
    unidade: "500g",
    categoria: "Proteínas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "ovos-codorna",
    nome: "Ovos de Codorna",
    preco: 25.0,
    unidade: "30 ovos",
    categoria: "Proteínas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "ovo-caipira-10",
    nome: "Ovo Caipira (cartela c/ 10)",
    preco: 15.0,
    unidade: "unidade",
    categoria: "Proteínas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
    descricao: "Ovos caipiras orgânicos.",
  },
  {
    id: "ovo-caipira-30",
    nome: "Ovo Caipira (cartela c/ 30)",
    preco: 40.0,
    unidade: "unidade",
    categoria: "Proteínas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
    descricao: "Ovos caipiras orgânicos.",
  },

  // ─── GRÃOS E CEREAIS ──────────────────────────────────────
  {
    id: "acucar-mascavo",
    nome: "Açúcar Mascavo",
    preco: 12.0,
    unidade: "500g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "arroz-sete-graos",
    nome: "Arroz Sete Grãos",
    preco: 10.0,
    unidade: "500g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "arroz-cateto-integral-vacuo",
    nome: "Arroz Cateto Integral Orgânico a Vácuo",
    preco: 28.0,
    unidade: "1kg",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "arroz-cateto-polido-vacuo",
    nome: "Arroz Cateto Polido Orgânico a Vácuo",
    preco: 20.0,
    unidade: "1kg",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "arroz-integral-organico",
    nome: "Arroz Integral Orgânico",
    preco: 15.0,
    unidade: "1kg",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "arroz-integral-organico-vacuo",
    nome: "Arroz Integral Orgânico a Vácuo",
    preco: 25.0,
    unidade: "1kg",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "arroz-misturadinho-vacuo",
    nome: "Arroz Misturadinho Orgânico a Vácuo",
    preco: 10.0,
    unidade: "500g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "arroz-parbolizado",
    nome: "Arroz Parbolizado Orgânico",
    preco: 20.0,
    unidade: "1kg",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "arroz-polido-organico",
    nome: "Arroz Polido Orgânico",
    preco: 15.0,
    unidade: "1kg",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "arroz-polido-organico-vacuo",
    nome: "Arroz Polido Orgânico a Vácuo",
    preco: 20.0,
    unidade: "1kg",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "aveia-em-laminas",
    nome: "Aveia em Lâminas Orgânica",
    preco: 14.0,
    unidade: "250g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "canjica-milho",
    nome: "Canjica de Milho Orgânica",
    preco: 18.0,
    unidade: "500g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "canjica-trigo",
    nome: "Canjica de Trigo Orgânica",
    preco: 8.0,
    unidade: "500g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "chia-graos",
    nome: "Chia em Grãos Orgânica",
    preco: 20.0,
    unidade: "250g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "chiaca-organica",
    nome: "Chiaça Orgânica",
    preco: 20.0,
    unidade: "250g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "erva-mate",
    nome: "Erva Mate Orgânica",
    preco: 26.0,
    unidade: "1kg",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "farinha-arroz",
    nome: "Farinha de Arroz Orgânica",
    preco: 20.0,
    unidade: "500g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "farinha-aveia",
    nome: "Farinha de Aveia Orgânica",
    preco: 15.0,
    unidade: "250g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "farinha-linhaca",
    nome: "Farinha de Linhaça Dourada Orgânica",
    preco: 18.0,
    unidade: "300g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "farinha-mandioca",
    nome: "Farinha de Mandioca Orgânica",
    preco: 18.0,
    unidade: "500g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "farinha-soja",
    nome: "Farinha de Soja",
    preco: 7.0,
    unidade: "300g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "farinha-trigo-branca",
    nome: "Farinha de Trigo Branca Orgânica",
    preco: 25.0,
    unidade: "500g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "farinha-trigo-integral",
    nome: "Farinha de Trigo Integral Orgânica",
    preco: 30.0,
    unidade: "500g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "feijao-carioquinha",
    nome: "Feijão Carioquinha",
    preco: 14.0,
    unidade: "500g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "feijao-de-corda",
    nome: "Feijão de Corda",
    preco: 12.0,
    unidade: "500g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "feijao-guandu",
    nome: "Feijão Guandu Seco",
    preco: 12.0,
    unidade: "500g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "feijao-preto",
    nome: "Feijão Preto",
    preco: 18.0,
    unidade: "500g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "feijao-vermelho",
    nome: "Feijão Vermelho",
    preco: 18.0,
    unidade: "500g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "flocos-arroz",
    nome: "Flocos de Arroz Orgânico",
    preco: 8.0,
    unidade: "100g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "flocos-aveia",
    nome: "Flocos de Aveia Orgânico",
    preco: 10.0,
    unidade: "250g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "flocos-milho",
    nome: "Flocos de Milho Orgânico",
    preco: 20.0,
    unidade: "250g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "fuba-milho",
    nome: "Fubá de Milho Orgânico",
    preco: 20.0,
    unidade: "500g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "grao-de-bico",
    nome: "Grão de Bico",
    preco: 25.0,
    unidade: "500g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "linhaca-dourada",
    nome: "Linhaça Dourada Grãos",
    preco: 20.0,
    unidade: "250g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "milho-pipoca",
    nome: "Milho de Pipoca",
    preco: 18.0,
    unidade: "500g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "quinoa",
    nome: "Quinoa em Grãos",
    preco: 25.0,
    unidade: "250g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "soja-graos",
    nome: "Soja em Grãos",
    preco: 15.0,
    unidade: "500g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "trigo-graos",
    nome: "Trigo em Grãos",
    preco: 18.0,
    unidade: "500g",
    categoria: "Grãos e Cereais",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },

  // ─── DERIVADOS E PROCESSADOS ──────────────────────────────
  {
    id: "banana-passa",
    nome: "Banana Passa",
    preco: 8.0,
    unidade: "60g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "banha-suina",
    nome: "Banha Suína Congelada",
    preco: 15.0,
    unidade: "300g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "biomassa-banana-verde",
    nome: "Biomassa Banana Verde",
    preco: 6.0,
    unidade: "250g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
    descricao: "Prebiótico natural. Ótimo para receitas sem glúten.",
  },
  {
    id: "bolacha-arroz-gergelim",
    nome: "Bolacha de Arroz Orgânico - Gergelim",
    preco: 15.0,
    unidade: "95g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "bolacha-arroz-linhaca",
    nome: "Bolacha de Arroz Orgânico - Linhaça",
    preco: 15.0,
    unidade: "95g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "bolacha-arroz-tradicional",
    nome: "Bolacha de Arroz Orgânico - Tradicional",
    preco: 15.0,
    unidade: "95g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "bucha-vegetal",
    nome: "Bucha Vegetal",
    preco: 7.0,
    unidade: "50g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "castanha-para",
    nome: "Castanha do Pará",
    preco: 20.0,
    unidade: "100g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "conserva-berinjela",
    nome: "Conserva de Berinjela",
    preco: 24.0,
    unidade: "600g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "conserva-cambuci",
    nome: "Conserva de Cambuci",
    preco: 20.0,
    unidade: "600g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "conserva-jilo",
    nome: "Conserva de Jiló",
    preco: 20.0,
    unidade: "600g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "conserva-pepininho",
    nome: "Conserva de Pepininho",
    preco: 20.0,
    unidade: "600g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "conserva-dedo-de-moca",
    nome: "Conserva de Dedo de Moça",
    preco: 20.0,
    unidade: "600g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "conserva-quiabo",
    nome: "Conserva de Quiabo",
    preco: 20.0,
    unidade: "600g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "cural-milho-verde",
    nome: "Cural de Milho Verde",
    preco: 10.0,
    unidade: "250g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "curcuma-conserva",
    nome: "Cúrcuma em Conserva",
    preco: 18.0,
    unidade: "250g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "curcuma-po",
    nome: "Cúrcuma em Pó Orgânica",
    preco: 25.0,
    unidade: "250g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "doce-banana",
    nome: "Doce de Banana Orgânica",
    preco: 15.0,
    unidade: "250g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "doce-mamao",
    nome: "Doce de Mamão",
    preco: 18.0,
    unidade: "500g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "extrato-tomate",
    nome: "Extrato de Tomate Orgânico",
    preco: 25.0,
    unidade: "600g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "geleia-amora-280",
    nome: "Geleia de Amora Orgânica (280g)",
    preco: 25.0,
    unidade: "280g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "geleia-amora-720",
    nome: "Geleia de Amora Orgânica (720g)",
    preco: 30.0,
    unidade: "720g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "geleia-morango",
    nome: "Geleia de Morango Orgânica",
    preco: 25.0,
    unidade: "295g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "geleia-uva",
    nome: "Geleia de Uva Orgânica",
    preco: 25.0,
    unidade: "280g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "geleia-mamao-laranja-limao",
    nome: "Geleia de Mamão, Laranja e Limão Orgânica",
    preco: 25.0,
    unidade: "240g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "geleia-mamao-pimenta",
    nome: "Geleia de Mamão c/ Pimenta Orgânica",
    preco: 25.0,
    unidade: "240g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "inhoque-biomassa",
    nome: "Inhoque de Biomassa de Banana",
    preco: 10.0,
    unidade: "pacote 500g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "inhoque-mandioca",
    nome: "Inhoque de Mandioca",
    preco: 17.0,
    unidade: "pacote 500g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "inhoque-mandioca-recheado",
    nome: "Inhoque de Mandioca Recheado",
    preco: 20.0,
    unidade: "pacote 500g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "licuri",
    nome: "Licuri",
    preco: 10.0,
    unidade: "100g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
    descricao: "Disponível: torrado c/ sal, sem sal ou com rapadura.",
  },
  {
    id: "mandioca-cozida-vacuo",
    nome: "Mandioca Cozida a Vácuo",
    preco: 10.0,
    unidade: "500g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "molho-tomate-580",
    nome: "Molho de Tomate Orgânico (580g)",
    preco: 25.0,
    unidade: "580g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "molho-tomate-800",
    nome: "Molho de Tomate Orgânico (800g)",
    preco: 28.0,
    unidade: "800g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "pasta-amendoim-natural",
    nome: "Pasta de Amendoim Natural",
    preco: 35.0,
    unidade: "240g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "pasta-amendoim-mel",
    nome: "Pasta de Amendoim com Mel",
    preco: 35.0,
    unidade: "240g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "pasta-amendoim-coco",
    nome: "Pasta de Amendoim c/ Açúcar de Coco",
    preco: 35.0,
    unidade: "240g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "piqui-organico",
    nome: "Piqui Orgânico",
    preco: 10.0,
    unidade: "500g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "polpa-abacaxi",
    nome: "Polpa de Abacaxi",
    preco: 7.0,
    unidade: "250g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "polpa-acerola",
    nome: "Polpa de Acerola",
    preco: 6.0,
    unidade: "250g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "polpa-amora",
    nome: "Polpa de Amora",
    preco: 6.0,
    unidade: "250g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "polpa-caju",
    nome: "Polpa de Cajú",
    preco: 8.0,
    unidade: "250g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "polpa-goiaba",
    nome: "Polpa de Goiaba",
    preco: 6.0,
    unidade: "250g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "polpa-graviola",
    nome: "Polpa de Graviola",
    preco: 8.0,
    unidade: "250g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "polpa-limao",
    nome: "Polpa de Limão",
    preco: 7.0,
    unidade: "250g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "polpa-manga",
    nome: "Polpa de Manga",
    preco: 6.0,
    unidade: "250g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "polpa-maracuja",
    nome: "Polpa de Maracujá",
    preco: 8.0,
    unidade: "250g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "polpa-tamarindo",
    nome: "Polpa de Tamarindo",
    preco: 8.0,
    unidade: "250g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "rapadura-organica",
    nome: "Rapadura Orgânica",
    preco: 20.0,
    unidade: "600g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "mini-rapadura",
    nome: "Mini Rapadura Orgânica",
    preco: 6.0,
    unidade: "100g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "sal-rosa-fino",
    nome: "Sal Rosa do Himalaia Fino",
    preco: 15.0,
    unidade: "250g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "sal-rosa-grosso",
    nome: "Sal Rosa do Himalaia Grosso",
    preco: 15.0,
    unidade: "250g",
    categoria: "Derivados e Processados",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },

  // ─── BEBIDAS ──────────────────────────────────────────────
  {
    id: "cachaca-socialista",
    nome: "Cachaça Artesanal A Socialista",
    preco: 70.0,
    unidade: "700ml",
    categoria: "Bebidas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
    descricao: "Cachaça artesanal produzida com cana orgânica.",
  },
  {
    id: "cerveja-stein-haus",
    nome: "Cerveja Stein Haus Blonde Ale S/ Glúten Orgânica",
    preco: 33.0,
    unidade: "500ml",
    categoria: "Bebidas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "suco-uva-1000",
    nome: "Suco de Uva Integral (1L)",
    preco: 28.0,
    unidade: "1L",
    categoria: "Bebidas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "suco-uva-1500",
    nome: "Suco de Uva Integral (1,5L)",
    preco: 30.0,
    unidade: "1,5L",
    categoria: "Bebidas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "suco-uva-organico",
    nome: "Suco de Uva Integral Orgânico",
    preco: 32.0,
    unidade: "1L",
    categoria: "Bebidas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "suco-amora-organico",
    nome: "Suco de Amora Integral Orgânico",
    preco: 30.0,
    unidade: "1L",
    categoria: "Bebidas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "suco-maca",
    nome: "Suco de Maçã Integral",
    preco: 28.0,
    unidade: "1L",
    categoria: "Bebidas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "suco-misto-manga-maca",
    nome: "Suco Misto Manga e Maçã Integral",
    preco: 11.0,
    unidade: "300ml",
    categoria: "Bebidas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "suco-misto-tangerina",
    nome: "Suco Misto Tangerina, Manga e Maçã Integral",
    preco: 11.0,
    unidade: "300ml",
    categoria: "Bebidas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },

  // ─── PÃES E PANIFICAÇÃO ───────────────────────────────────
  {
    id: "bolo-mandioca",
    nome: "Bolo de Mandioca",
    preco: 25.0,
    unidade: "650g",
    categoria: "Pães e Panificação",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
    descricao: "Bolo artesanal de mandioca.",
  },
  {
    id: "pao-integral",
    nome: "Pão Integral",
    preco: 20.0,
    unidade: "650g",
    categoria: "Pães e Panificação",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "pao-integral-sementes",
    nome: "Pão Integral com Sementes",
    preco: 25.0,
    unidade: "650g",
    categoria: "Pães e Panificação",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "pao-tradicional",
    nome: "Pão Tradicional",
    preco: 17.0,
    unidade: "650g",
    categoria: "Pães e Panificação",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "pao-vegano",
    nome: "Pão Artesanal Vegano",
    preco: 20.0,
    unidade: "650g",
    categoria: "Pães e Panificação",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },

  // ─── MEL E APÍCOLAS ───────────────────────────────────────
  {
    id: "mel-silvestre-cipo-uva-500",
    nome: "Mel Silvestre Cipó Uva (500g)",
    preco: 50.0,
    unidade: "500g",
    categoria: "Mel e Apícolas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
    descricao: "Mel silvestre extraído de cipó uva.",
  },
  {
    id: "mel-silvestre-cipo-uva-350",
    nome: "Mel Silvestre Cipó Uva (350g)",
    preco: 40.0,
    unidade: "350g",
    categoria: "Mel e Apícolas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "mel-silvestre-gengibre",
    nome: "Mel Silvestre com Gengibre",
    preco: 45.0,
    unidade: "350g",
    categoria: "Mel e Apícolas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "mel-silvestre-guaco",
    nome: "Mel Silvestre com Guaco",
    preco: 45.0,
    unidade: "350g",
    categoria: "Mel e Apícolas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "mel-silvestre-jatai",
    nome: "Mel Silvestre Jataí",
    preco: 50.0,
    unidade: "70g",
    categoria: "Mel e Apícolas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
    descricao: "Mel da abelha Jataí — sem ferrão, sabor suave.",
  },
  {
    id: "mel-silvestre",
    nome: "Mel Silvestre",
    preco: 35.0,
    unidade: "280g",
    categoria: "Mel e Apícolas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
  },
  {
    id: "polen",
    nome: "Pólen",
    preco: 40.0,
    unidade: "150g",
    categoria: "Mel e Apícolas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
    descricao: "Superalimento rico em proteínas e vitaminas.",
  },
  {
    id: "propolis-verde",
    nome: "Própolis Verde",
    preco: 35.0,
    unidade: "30ml",
    categoria: "Mel e Apícolas",
    emEstoque: false,
    naCestaGrande: false,
    naCestaPequena: false,
    descricao: "Própolis verde — antibiótico natural.",
  },
];

// Configuração inicial das cestas (vazia — Elizete monta semanalmente)
export const CONFIG_CESTA_INICIAL: ConfigCestaSemana = {
  dataAtualizacao: new Date().toISOString(),
  cestaGrandeAtiva: true,
  cestaPequenaAtiva: true,
};

// Número do WhatsApp da cooperativa (formato internacional sem +)
// Substitua pelo número real da Elizete antes de ir para produção!
export const WHATSAPP_NUMERO = "5517992702323";

// Endereço de retirada
export const ENDERECO_RETIRADA =
  "Bela Liria: Rua Cerqueira Cesar, 1826, Jardim Sumaré";
